#!/usr/bin/env python3
"""Deployment service with dashboard, channel API, and restricted HLS gateway.

The gateway only proxies URLs belonging to configured channel sources.
It is intentionally not an arbitrary/open URL proxy.
"""

from __future__ import annotations

import asyncio
import base64
import ipaddress
import logging
import os
import socket
from pathlib import Path
from urllib.parse import urljoin, urlparse

import aiohttp
import m3u8
from aiohttp import web

from scraper import AccessDeniedError, Channel, ChannelWorker, HLSClient, load_channels


LOG = logging.getLogger("livechannels.service")


def channel_id(channel: Channel) -> str:
    import re

    return re.sub(r"[^a-z0-9]+", "-", channel.name.lower()).strip("-") or "channel"


def encode_url(url: str) -> str:
    return base64.urlsafe_b64encode(url.encode("utf-8")).decode("ascii").rstrip("=")


def decode_url(value: str) -> str:
    padding = "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode((value + padding).encode("ascii")).decode("utf-8")


def host_allowed(url: str, allowed_hosts: set[str]) -> bool:
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        return False

    host = parsed.hostname.lower()
    if host in allowed_hosts:
        return True

    try:
        ip = ipaddress.ip_address(host)
        return not (
            ip.is_private
            or ip.is_loopback
            or ip.is_link_local
            or ip.is_reserved
            or ip.is_multicast
            or ip.is_unspecified
        )
    except ValueError:
        # For a hostname, require explicit allowlisting.
        return False


def channel_lookup(channels: list[Channel]) -> dict[str, Channel]:
    return {channel_id(ch): ch for ch in channels}


def build_dashboard(channels: list[Channel], request: web.Request) -> str:
    base = str(request.url.origin())
    rows = []

    for channel in channels:
        cid = channel_id(channel)
        stream = f"{base}/stream/{cid}/master.m3u8"
        rows.append(
            f"""
            <tr>
              <td><strong>{web.html_escape(channel.name)}</strong></td>
              <td><code>{web.html_escape(channel.url)}</code></td>
              <td>
                <button onclick="copyText('{web.html_escape(stream)}')">Copy M3U8</button>
                <a href="{web.html_escape(stream)}" target="_blank" rel="noopener">Open</a>
              </td>
            </tr>
            """
        )

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LiveChannels Scraper</title>
<style>
body{{font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#101114;color:#eee;margin:0}}
main{{max-width:1200px;margin:40px auto;padding:0 20px}}
h1{{margin-bottom:6px}} .sub{{color:#9aa0a6;margin-bottom:24px}}
table{{width:100%;border-collapse:collapse;background:#181a20;border-radius:12px;overflow:hidden}}
th,td{{padding:14px;text-align:left;border-bottom:1px solid #2a2d35;vertical-align:top}}
code{{word-break:break-all;color:#a8d8ff}}
button,a{{display:inline-block;margin:3px;padding:8px 12px;border-radius:8px;border:0;background:#2a6df4;color:#fff;text-decoration:none;cursor:pointer}}
a{{background:#3a3f4b}}
.note{{margin-top:22px;padding:14px;background:#181a20;border-radius:10px;color:#b7bcc6}}
</style>
<script>
async function copyText(text){{
  await navigator.clipboard.writeText(text);
  alert("M3U8 URL copied");
}}
</script>
</head>
<body>
<main>
<h1>LiveChannels Scraper</h1>
<div class="sub">{len(channels)} configured channel(s)</div>
<table>
<thead><tr><th>Channel</th><th>Configured source</th><th>Playback URL</th></tr></thead>
<tbody>{''.join(rows)}</tbody>
</table>
<div class="note">
The displayed M3U8 URLs are generated by this application's controlled HLS gateway.
Only configured channel sources are eligible; this service is not an arbitrary URL proxy.
</div>
</main>
</body>
</html>"""


async def run_service() -> None:
    logging.basicConfig(
        level=os.getenv("LOG_LEVEL", "INFO").upper(),
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )

    output_dir = Path(os.getenv("OUTPUT_DIR", "data"))
    config_path = Path(os.getenv("CHANNEL_CONFIG", "channels.json"))
    append_ts = os.getenv("APPEND_TS", "false").lower() in {"1", "true", "yes", "on"}

    channels = load_channels(config_path, output_dir)
    if not channels:
        raise RuntimeError("No enabled channels configured")

    by_id = channel_lookup(channels)
    allowed_hosts_by_channel: dict[str, set[str]] = {}
    for channel in channels:
        host = urlparse(channel.url).hostname
        allowed_hosts_by_channel[channel_id(channel)] = {host.lower()} if host else set()
    stop = asyncio.Event()

    connector = aiohttp.TCPConnector(
        limit=50,
        limit_per_host=8,
        ttl_dns_cache=300,
    )

    timeout = float(os.getenv("UPSTREAM_TIMEOUT", "10"))
    retries = int(os.getenv("UPSTREAM_RETRIES", "4"))

    async with aiohttp.ClientSession(connector=connector) as session:
        client = HLSClient(session, retries=retries, timeout=timeout)

        workers = [ChannelWorker(channel, client, stop, append_ts) for channel in channels]
        tasks = [
            asyncio.create_task(worker.run(), name=f"channel:{channel.name}")
            for worker, channel in zip(workers, channels)
        ]

        async def health(_: web.Request) -> web.Response:
            return web.json_response({
                "status": "ok",
                "service": "livechannels-scraper",
                "workers": len(channels),
            })

        async def api_channels(_: web.Request) -> web.Response:
            return web.json_response({
                "success": True,
                "channels": [
                    {
                        "id": channel_id(ch),
                        "name": ch.name,
                        "sourceUrl": ch.url,
                        "gatewayUrl": f"/stream/{channel_id(ch)}/master.m3u8",
                    }
                    for ch in channels
                ],
            })

        async def root(request: web.Request) -> web.Response:
            return web.Response(
                text=build_dashboard(channels, request),
                content_type="text/html",
            )

        async def stream(request: web.Request) -> web.StreamResponse:
            cid = request.match_info["channel_id"]
            channel = by_id.get(cid)
            if not channel:
                raise web.HTTPNotFound(text="Unknown channel")

            requested_url = request.query.get("u")
            target = decode_url(requested_url) if requested_url else channel.url

            allowed_hosts = allowed_hosts_by_channel.setdefault(cid, set())

            if not host_allowed(target, allowed_hosts):
                raise web.HTTPForbidden(text="Target is not an allowed configured source")

            try:
                body, final_url = await client.fetch_text(target, {
                    "Accept": "application/vnd.apple.mpegurl, application/x-mpegURL, */*",
                    **{k: v for k, v in channel.headers.items() if k.lower() != "host"},
                })
            except AccessDeniedError as exc:
                raise web.HTTPBadGateway(text=str(exc)) from exc

            # Add the final redirect hostname to the in-request allowlist only when
            # it is a publicly routable hostname reached from an allowed source.
            final_host = urlparse(final_url).hostname
            if final_host:
                try:
                    addr = socket.gethostbyname(final_host)
                    ip = ipaddress.ip_address(addr)
                    if not (
                        ip.is_private
                        or ip.is_loopback
                        or ip.is_link_local
                        or ip.is_reserved
                        or ip.is_multicast
                        or ip.is_unspecified
                    ):
                        allowed_hosts.add(final_host.lower())
                        allowed_hosts_by_channel[cid] = allowed_hosts
                except (OSError, ValueError):
                    pass

            if body.lstrip().startswith("#EXTM3U"):
                playlist = m3u8.loads(body, uri=final_url)

                # Refuse encrypted/protected playlists rather than attempting to
                # bypass or unwrap keys.
                if playlist.keys and any(key is not None for key in playlist.keys):
                    raise web.HTTPBadGateway(text="Encrypted/protected HLS is not handled")

                if playlist.is_variant:
                    for item in playlist.playlists:
                        absolute = urljoin(final_url, item.uri)
                        item.uri = (
                            f"/stream/{cid}/master.m3u8?u={encode_url(absolute)}"
                        )
                else:
                    for index, segment in enumerate(playlist.segments):
                        absolute = urljoin(final_url, segment.uri)
                        if not host_allowed(absolute, allowed_hosts):
                            raise web.HTTPBadGateway(
                                text=f"Segment host is outside the configured source: {urlparse(absolute).hostname}"
                            )
                        segment.uri = f"/stream/{cid}/segment?u={encode_url(absolute)}"

                rendered = playlist.dumps()
                return web.Response(
                    body=rendered.encode("utf-8"),
                    content_type="application/vnd.apple.mpegurl",
                    headers={"Cache-Control": "no-store"},
                )

            raise web.HTTPBadGateway(text="Configured source did not return an HLS playlist")

        async def segment(request: web.Request) -> web.StreamResponse:
            cid = request.match_info["channel_id"]
            channel = by_id.get(cid)
            if not channel:
                raise web.HTTPNotFound(text="Unknown channel")

            encoded = request.query.get("u")
            if not encoded:
                raise web.HTTPBadRequest(text="Missing segment URL")

            try:
                target = decode_url(encoded)
            except Exception as exc:
                raise web.HTTPBadRequest(text="Invalid encoded URL") from exc

            allowed_hosts = allowed_hosts_by_channel.setdefault(cid, set())
            if not host_allowed(target, allowed_hosts):
                raise web.HTTPForbidden(text="Segment is outside the configured source")

            try:
                payload = await client.fetch_bytes(
                    target,
                    {
                        "Accept": "*/*",
                        **{k: v for k, v in channel.headers.items() if k.lower() != "host"},
                    },
                )
            except AccessDeniedError as exc:
                raise web.HTTPBadGateway(text=str(exc)) from exc

            return web.Response(
                body=payload,
                content_type="video/mp2t"
                if target.lower().split("?", 1)[0].endswith(".ts")
                else "application/octet-stream",
                headers={"Cache-Control": "no-store"},
            )

        app = web.Application(client_max_size=2 * 1024 * 1024)
        app.router.add_get("/", root)
        app.router.add_get("/health", health)
        app.router.add_get("/api/channels", api_channels)
        app.router.add_get("/stream/{channel_id}/master.m3u8", stream)
        app.router.add_get("/stream/{channel_id}/segment", segment)

        runner = web.AppRunner(app)
        await runner.setup()

        port = int(os.getenv("PORT", "8080"))
        site = web.TCPSite(runner, "0.0.0.0", port)
        await site.start()

        LOG.info("dashboard listening on 0.0.0.0:%s", port)
        LOG.info("configured channels: %d", len(channels))

        try:
            await asyncio.Event().wait()
        finally:
            stop.set()
            for task in tasks:
                task.cancel()
            await asyncio.gather(*tasks, return_exceptions=True)
            await runner.cleanup()


def main() -> None:
    asyncio.run(run_service())


if __name__ == "__main__":
    main()
